### ISSUE TITLE
Cursor retrieves null after DB upgrade

### ISSUE THREAD

**Issue by pdmholden** [pdmholden/bcclaarrest#12]
In testing upgrade from 0.1 to 0.2, the Cursor in TableOfContents gets a null value for the first row. The result is a crash when ListArray tries to create the list to display. Debug output:

`V/RenderScript_jni(  195): surfaceDestroyed
I/TableOfContents( 6058): NUMROWS: 5
I/TableOfContents( 6058): 0: null
I/TableOfContents( 6058): 1: Introduction
I/TableOfContents( 6058): 2: The Police and Arrest
I/TableOfContents( 6058): 3: Being Detained
I/TableOfContents( 6058): 4: When You are Arrested
D/AndroidRuntime( 6058): Shutting down VM`

And the NullPointerException stack trace:

`D/AndroidRuntime( 6058): Shutting down VM
W/dalvikvm( 6058): threadid=1: thread exiting with uncaught exception (group=0x40015560)
E/AndroidRuntime( 6058): FATAL EXCEPTION: main
E/AndroidRuntime( 6058): java.lang.NullPointerException
E/AndroidRuntime( 6058):        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:355)
E/AndroidRuntime( 6058):        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
E/AndroidRuntime( 6058):        at android.widget.AbsListView.obtainView(AbsListView.java:1430)
E/AndroidRuntime( 6058):        at android.widget.ListView.makeAndAddView(ListView.java:1745)`

**Comment by pdmholden** [comment]
There is an ugly workaround: After updating to 0.2 the user can use the Android app manager to "clear data". The when the app is started, it will create a fresh database (rather than overwriting the old one) and will have no problem.

Currently the installed base of users for 0.1 is 2.

**Comment by pdmholden** [comment]
Question with no answers posed on SO:

http://stackoverflow.com/q/13435112/46461
